schemas:
  - name: "wordpress"
    path: "https://github.com/k1LoW/tbls-ask/blob/main/testdata/wordpress.json"
  - name: "test"
    path: "https://github.com/k1LoW/tbls/blob/main/testdata/testdb.json"