apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbls-ask-agent-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbls-ask-agent-slack
  template:
    metadata:
      labels:
        app: tbls-ask-agent-slack
    spec:
      containers:
      - name: tbls-ask-agent-slack
        imagePullPolicy: Always
        image: ghcr.io/kromiii/tbls-ask-agent-slack:latest
        env:
          - name: SLACK_APP_TOKEN
            valueFrom:
              secretKeyRef:
                name: tbls-ask-agent-slack
                key: slack-app-token
          - name: SLACK_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: tbls-ask-agent-slack
                key: slack-oauth-token
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: tbls-ask-agent-slack
                key: gemini-api-key
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: tbls-ask-agent-slack
                key: github-token
          - name: MODEL_NAME
            value: gemini-1.5-pro
        volumeMounts:
        - name: tbls-schemas
          mountPath: /app/schemas
      volumes:
      - name: tbls-schemas
        configMap:
          name: tbls-schemas
