apiVersion: v1
kind: Service
metadata:
  name: tbls-ask-agent-slack
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  selector:
    app: tbls-ask-agent-slack
